manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Thomas-Nurse
      url-base: https://github.com/Thomas-Nurse
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: satori-split-zmk-config
      remote: Thomas_Nurse
      revision: master
  self:
    path: config
